# Site Settings
lang: en
title: Pickaway County Democratic Party
#tagline: Bulma Clean Theme
email: webmaster@pickawaydems.org
description: >
  The demo site for Bulma Clean Theme, made for Jekyll and GitHub pages websites
baseurl: ""
url: "https://pickawaydemocrats.github.io"
permalink: pretty
remote_theme: chrisrhymes/bulma-clean-theme
fixed_navbar: top
footer_menu: footer_menu
#favicon: /path/to/favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

social-network-links:
  email: "pickawaycountydemocrats@gmail.com"
  facebook: profile.php?id=100064353652617
  twitter: pickawaydems
  instagram: pickawaydems
  telephone: 7408335144
  
# Disqus Comments
#disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  #shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
